language: go
go_import_path: github.com/shurcooL/vfsgen
env:
  global:
    - GO111MODULE=on
go:
  - stable
matrix:
  fast_finish: true
install: true
script:
  - go generate ./...
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go vet ./...
  - go test -v -race ./...
